name: flutter_password_cracker
description: "A proof-of-concept app that demonstrates native Rust integration for CPU-intensive cryptographic tasks, with real-time streaming updates back to the Flutter UI."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_rust_bridge: 2.12.0
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
