// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_hash`, `index_to_string`

String hashString({required String input}) =>
    RustLib.instance.api.crateApiHashString(input: input);

Stream<CrackProgress> bruteForceCrack({required String targetHash}) =>
    RustLib.instance.api.crateApiBruteForceCrack(targetHash: targetHash);

class CrackProgress {
  final String currentAttempt;
  final BigInt totalAttempts;
  final double hashesPerSec;
  final double elapsedSecs;
  final bool isFound;
  final String? result;

  const CrackProgress({
    required this.currentAttempt,
    required this.totalAttempts,
    required this.hashesPerSec,
    required this.elapsedSecs,
    required this.isFound,
    this.result,
  });

  @override
  int get hashCode =>
      currentAttempt.hashCode ^
      totalAttempts.hashCode ^
      hashesPerSec.hashCode ^
      elapsedSecs.hashCode ^
      isFound.hashCode ^
      result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrackProgress &&
          runtimeType == other.runtimeType &&
          currentAttempt == other.currentAttempt &&
          totalAttempts == other.totalAttempts &&
          hashesPerSec == other.hashesPerSec &&
          elapsedSecs == other.elapsedSecs &&
          isFound == other.isFound &&
          result == other.result;
}
